### ISSUE TITLE
How did you load the data FROM daylightmap INTO Neo4J

### ISSUE THREAD

**Issue by jamessdixon** [johnymontana/geospatial-graph-demos#1]
Do you have a code sample for extracting what I want from https://daylightmap.org/earth/ into my instance of Neo4J?

**Comment by jamessdixon** [comment]
all set - I read the docs - thanks

**Comment by johnymontana** [comment]
Good question! I updated the README to include a more explicit link to the Python code used to import points of interest. For others, you can find it here: https://github.com/johnymontana/daylight-earth-graph/blob/main/POI_import.ipynb
